# importation of libraries

In [1]:
# imports

import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.linear_model import LogisticRegression,LinearRegression,Ridge
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


# loading the dataset using pandas and cleaning the dataset.
the cell bellow we load the csv file using pandas.
then we use .head() to beable to see the 1st 5 rows of the dataset.

In [2]:
df=pd.read_csv("bigml_59c28831336c6604c800002a.csv")

In [3]:
df.head()

state  account length  area code phone number international plan  \
0    KS             128        415     382-4657                 no   
1    OH             107        415     371-7191                 no   
2    NJ             137        415     358-1921                 no   
3    OH              84        408     375-9999                yes   
4    OK              75        415     330-6626                yes   

  voice mail plan  number vmail messages  total day minutes  total day calls  \
0             yes                     25              265.1              110   
1             yes                     26              161.6              123   
2              no                      0              243.4              114   
3              no                      0              299.4               71   
4              no                      0              166.7              113   

   total day charge  ...  total eve calls  total eve charge  \
0             45.07  ...               99             16.78   
1             27.47  ...              103             16.62   
2             41.38  ...              110             10.30   
3             50.90  ...               88              5.26   
4             28.34  ...              122             12.61   

   total night minutes  total night calls  total night charge  \
0                244.7                 91               11.01   
1                254.4                103               11.45   
2                162.6                104                7.32   
3                196.9                 89                8.86   
4                186.9                121                8.41   

   total intl minutes  total intl calls  total intl charge  \
0                10.0                 3               2.70   
1                13.7                 3               3.70   
2                12.2                 5               3.29   
3                 6.6                 7               1.78   
4                10.1                 3               2.73   

   customer service calls  churn  
0                       1  False  
1                       1  False  
2                       0  False  
3                       2  False  
4                       3  False  

[5 rows x 21 columns]

### finding the .info()
in the cell bellow we see that there are a total of 3333 rows and 21 columns.
we are also able to identify that there are no missing values in this dataset since the non_null count of all the columns add up to 3333.we are also able to identify the data type of each column.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   state                   3333 non-null   object 
 1   account length          3333 non-null   int64  
 2   area code               3333 non-null   int64  
 3   phone number            3333 non-null   object 
 4   international plan      3333 non-null   object 
 5   voice mail plan         3333 non-null   object 
 6   number vmail messages   3333 non-null   int64  
 7   total day minutes       3333 non-null   float64
 8   total day calls         3333 non-null   int64  
 9   total day charge        3333 non-null   float64
 10  total eve minutes       3333 non-null   float64
 11  total eve calls         3333 non-null   int64  
 12  total eve charge        3333 non-null   float64
 13  total night minutes     3333 non-null   float64
 14  total night calls       3333 non-null   

### Droping the non useful columns

In [5]:
df. drop (columns=["phone number"] , inplace=True)

converting churn to binary

In [6]:
df['churn'] = df['churn'].map({True: 1 , False: 0})

### encoding the categorical variables
using the get_dummies()

In [7]:
df=pd.get_dummies(df, columns=["state","international plan","voice mail plan"], drop_first=True)

In [8]:
df.head()

account length  area code  number vmail messages  total day minutes  \
0             128        415                     25              265.1   
1             107        415                     26              161.6   
2             137        415                      0              243.4   
3              84        408                      0              299.4   
4              75        415                      0              166.7   

   total day calls  total day charge  total eve minutes  total eve calls  \
0              110             45.07              197.4               99   
1              123             27.47              195.5              103   
2              114             41.38              121.2              110   
3               71             50.90               61.9               88   
4              113             28.34              148.3              122   

   total eve charge  total night minutes  ...  state_TX  state_UT  state_VA  \
0             16.78                244.7  ...         0         0         0   
1             16.62                254.4  ...         0         0         0   
2             10.30                162.6  ...         0         0         0   
3              5.26                196.9  ...         0         0         0   
4             12.61                186.9  ...         0         0         0   

   state_VT  state_WA  state_WI  state_WV  state_WY  international plan_yes  \
0         0         0         0         0         0                       0   
1         0         0         0         0         0                       0   
2         0         0         0         0         0                       0   
3         0         0         0         0         0                       1   
4         0         0         0         0         0                       1   

   voice mail plan_yes  
0                    1  
1                    1  
2                    0  
3                    0  
4                    0  

[5 rows x 69 columns]

### identifying the features and the target.
spliting the data into X and y

In [9]:
X = df.drop(columns=["churn"],axis=1)
y = df["churn"]

### train_test of the split
the test is 20% while the train is 80% and a random_state of 42.stratify=y to ensure same propotion of each class that appears in y_train and y_test.

In [10]:
X_train ,X_test ,y_train ,y_test = train_test_split(X,y,test_size=0.2, random_state=42, stratify=y)

### scaling
to prevent data leakage and ensure model's evaluation is trustworthy.by using fit scaler only on training data and apply same scaling to test data

In [11]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### logistic regression.

In [12]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

### making prediction using the model.

In [19]:
y_pred = model.predict(X_test_scaled)
y_pred[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

### evaluating the model.

In [14]:
print("classification Report:\n",classification_report(y_test, y_pred))
print("accuracy:",accuracy_score(y_test, y_pred))
print("confusion matrix:\n",confusion_matrix(y_test, y_pred))

classification Report:
               precision    recall  f1-score   support

           0       0.89      0.96      0.92       570
           1       0.57      0.27      0.36        97

    accuracy                           0.86       667
   macro avg       0.73      0.62      0.64       667
weighted avg       0.84      0.86      0.84       667

accuracy: 0.863568215892054
confusion matrix:
 [[550  20]
 [ 71  26]]


### propability prediction

In [18]:
y_pred = model.predict_proba(X_test_scaled)[:,1]
y_pred[:10]

array([0.18514538, 0.14255295, 0.11830867, 0.14299834, 0.36171738,
       0.05563994, 0.30276243, 0.11726586, 0.03391856, 0.11105139])

# Decision tree model

importation of an important model.

In [16]:
from sklearn.tree import DecisionTreeClassifier

In [24]:
X = df.drop(columns=["churn"],axis=1)
y = df["churn"]

In [25]:
X_train ,X_test ,y_train ,y_test = train_test_split(X,y,test_size=0.2, random_state=42, stratify=y)

creating the model

In [26]:
df_model = DecisionTreeClassifier(criterion="gini",max_depth=5,random_state=42)

train(fit) the model

In [27]:
df_model.fit(X_train,y_train)#to capture non linear relationships

DecisionTreeClassifier(max_depth=5, random_state=42)

making predictions

In [28]:
y_pred2=df_model.predict(X_test)
y_pred2[:10]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

### evaluating the model

In [29]:
print("classification Report:\n",classification_report(y_test, y_pred2))
print("accuracy:",accuracy_score(y_test, y_pred2))
print("confusion matrix:\n",confusion_matrix(y_test, y_pred2))

classification Report:
               precision    recall  f1-score   support

           0       0.94      0.96      0.95       570
           1       0.75      0.62      0.68        97

    accuracy                           0.91       667
   macro avg       0.84      0.79      0.81       667
weighted avg       0.91      0.91      0.91       667

accuracy: 0.9145427286356822
confusion matrix:
 [[550  20]
 [ 37  60]]


comparision between logistic regression and decision tree.

In [31]:
log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train_scaled, y_train)
y_pred_log = log_model.predict(X_test_scaled)
print("logistic accuracy:",accuracy_score(y_test,y_pred_log))
print("decision tree accuracy:",accuracy_score(y_test,y_pred2))

logistic accuracy: 0.863568215892054
decision tree accuracy: 0.9145427286356822
